services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: studiobooking
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/studiobooking
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    environment:
      # The API URL is baked into the frontend build and accessed by the
      # browser, so we must expose the backend on the host network.
      VITE_API_URL: http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: